generator/_config.yml, generator/source/_includes/head.html
=> Add google analytics

generator/Dockerfile
Signed-off-by: Sutrannu <bbetts@bitwise.io>
=> Update ruby-image version for compatibility

generator/entrypoint-gen.sh
Signed-off-by: Sutrannu <bbetts@bitwise.io>
=> Do not make unnecessary symlink

README.md
- Add repo description with link to grid.hyperledger.org
- Retitle sections
- Clarify build procedure, number steps, and turn linter info into note
- Correct and clarify info about website content
- Fix license wording and add links
=> Expand and improve grid-website README

generator/_config.yml
=> Change twitter link to point to Grid tweets

generator/source/community/code_of_conduct.rst, generator/source/community/community.rst, generator/source/community/contributing.rst, generator/source/community/join_the_discussion.rst
Community:
- Add a high-level summary of Grid "areas" for which we encourage feedback
- Expand each link's text for friendliness and clarity
Code of Conduct:
- Correct link to Hyperledger's code of contact page (it moved)
- Also fix grammar in the first sentence
Contributing:
- Add entry for grid-contrib under "Ways you can contribute"
- Make minor wording changes and link fixes for clarity and friendliness
- Fix document structure (add Header markup)
Joining the Discussion:
- Add info about a Linux Foundation ID
- Reword for friendliness
- Remove headers (they take up too much space)
- Fix blockquote format issue
=> Update Community pages for Grid website

generator/source/docs/docs.rst
- Add intro text
- Clarify "nightly master" for non-developers
- Add note on incubation status and frequent doc changes
=> Update and expand Docs page on Grid website

generator/source/faq/faq.rst
=> Fix typo in FAQ link

README.md, docker-compose.yaml
Updates README and Docker tooling to match the new repository name.
=> Change "grid-website" to "grid-docs"

_includes/0.1/left_sidebar.html, docs/0.1/cli_references.md, docs/0.1/grid_on_splinter.md
1) Expands Grid CLI reference to include output from help commands
2) Adds documentation on how to run grid on splinter
=> Ryanlassigbanks add grid client content

_includes/community/left_sidebar.html, community/licensing.md, community/repositories.md
=> Add Licensing & Repositories pages for Community

_includes/community/left_sidebar.html, community/index.md, community/join_the_discussion.md
=> Merge Contributing info from FAQ and website

releases/0.1/download.md
=> Add download page

_includes/0.1/left_sidebar.html, docs/0.1/building_grid.md
=> Add Building Grid topic (from Grid README)

_includes/0.1/left_sidebar.html, docs/0.1/references/rust_sdk/index.md
=> Move grid-sdk link from doc TOC to ref topic

docs/grid/nightly/master/about_grid.md, docs/grid/nightly/master/app_developers_guide.md, docs/grid/nightly/master/cli_references.md, docs/grid/nightly/master/contents.md, docs/grid/nightly/master/glossary.md, docs/grid/nightly/master/grid_sdk.md, docs/grid/nightly/master/introduction.md, docs/grid/nightly/master/references.md, docs/grid/nightly/master/rest_api.md, docs/grid/nightly/master/transaction_family_specifications.md, docs/grid/nightly/master/transaction_family_specifications/grid_schema_family_specification.md, docs/grid/nightly/master/transaction_family_specifications/grid_track_and_trace_family_specification.md, docs/grid/nightly/master/transaction_family_specifications/pike_transaction_family.md
Files that have been deleted will redirect to the doc landing page (/docs/0.1/)
=> Add redirects for doc files from prev website

about.md, faq/faq.md, faq/grid.md, faq/index.md
=> Add redirects for deleted website (non-doc) pages

Jenkinsfile
=> Publish grid-website to Docker Hub after successful build

docs/0.1/grid_product.md
Improve the wording in the last sentence of the Grid Product overview per a helpful reviewer suggestion.
=> Fix wording in Grid Product overview

Jenkinsfile
=> Only publish docker images on master merges

_includes/0.1/left_sidebar.html, docs/0.1/grid_location_smart_contract_specification.md
=> Add location transaction family spec documentation

community/roadmap.md
The RFC has been accepted, so updated that link and switched status to
'Under Development'.
=> Update status of Location in the 0.1 roadmap section

ci/lint.dockerfile
Incrementing mdl to newest version.
Signed-off-by: David Cecchi <David_Cecchi@cargill.com>
=> Update to latest mdl

docs/0.1/references/cli/grid-product.1.md
=> Add Grid Product subcommand man page

docs/0.1/references/api/index.md, docs/0.1/references/api/openapi.yaml
This updates the openapi spec to match the version in the
Hyperledger Grid repository.
=> Update openapi.yaml file

_includes/community/left_sidebar.html, community/best_practices/adding_product_properties.md
Adds initial section about best practices around adding new product
properties to the products schema.
=> Add adding product properties section to community page

docs/0.1/creating_products.md
This PR updates the Product how-to procedure to work with the updated
CLI commands and reflect the Grid on Splinter example walkthrough in the
Grid repo.
=> Update Product how-to procedure

_includes/0.1/left_sidebar.html, docs/0.1/grid_product_smart_contract_specification.md
=> Add grid product smart contract specification

docs/0.1/grid_location.md
Signed-off-by: Jessie Zamzow <jessie_zamzow@cargill.com>
=> Clean up location capitalization

_includes/0.1/left_sidebar.html
=> Add location overview to sidebar

docs/0.1/creating_organizations.md, docs/0.1/creating_products.md
This PR fixes a few small issues with the docs
=> Small doc updates and fixes

releases/0.1/download.md, releases/0.1/index.md
Adds content to the downloads and release pages
=> Add Grid 0.1 release documentation

ci/website.dockerfile
=> Add 0.2 REST API docs to publishable docker image

docs/0.2/pike_smart_contract_specification.md
This updates the Pike smart contract specification document for the Pike
2.0 update. This updates info about addressing, protos, and actions.
=> Add update spec for Pike 2

docs/0.2/grid_pike.md
This adds a brief feature overview for the Grip Pike feature.
=> Add Pike overview

community/planning/batch_submitter.md, community/planning/features.md
=> Add batch processor feature document

_includes/community/left_sidebar.html, community/best_practices/release_checklist.md
=> Add release checklist

docs/0.2/references/api/openapi.yaml
Brings the spec up to date with the working spec in the Grid repo
=> Update dev REST API specification

docs/0.2/creating_products.md, docs/0.2/creating_products_with_nonstandard_attrs.md, docs/0.2/creating_schemas.md, docs/0.2/references/product/additional_attributes.yaml, docs/0.2/references/product/example_product.xml, docs/0.2/references/product/nonstandard_product_schema.yaml
This updates the creating schemas and creating products how-to guides to
reflect the updates made to Product. This includes information about
GDSN product definitions and update product definition files.
=> Update docs for product update

_includes/0.2/left_sidebar.html, docs/0.2/grid_pike.md, docs/0.2/images/pike_diagrams/alpha-beta-gamma.svg, docs/0.2/images/pike_diagrams/alpha-beta.svg, docs/0.2/images/pike_diagrams/alpha-full.svg, docs/0.2/images/pike_diagrams/alpha-insp.svg, docs/0.2/images/pike_diagrams/delta-beta.svg, docs/0.2/images/pike_diagrams/delta.svg, docs/0.2/images/pike_diagrams/full.svg, docs/0.2/using_pike.md
- Adds a link to the delegation example from the feature page for more high-level info
- Replaces the condensed example with the full example from the RFC
- Adds diagrams for each step of the example
=> Add delegation example diagrams

docs/0.2/creating_products_with_nonstandard_attrs.md
This was identified as a possible point of confusion
=> Add note about XML strings in YAML file

_includes/releases/left_sidebar.html, releases/0.2/download.md, releases/0.2/index.md
=> Add 0.2 release info

docs/0.2/references/addressing_reference.md
Updates the Pike prefix and adds the role object prefix
=> Update addressing reference for Pike v2

docs/0.2/creating_schemas.md
=> Fix description of schema

docs/0.2/creating_products.md, docs/0.2/references/product/example_product.xml
This PR contains a couple small changes to the Creating Products section of the docs. This fixes a small issue with the example product XML file and adds a missing comma.
=> Update Creating Products section

_includes/releases/left_sidebar.html, releases/0.2/upgrading/README.md, releases/0.2/upgrading/grid-v0.2.1-from-v0.1.2.md
To view, run `just run` and navigate to localhost:8080. Upgrading guide is at http://localhost:8080/releases/0.2/upgrading/.
=> Add upgrading guide for 0.2.1

docs/0.2/creating_products.md, docs/0.3/creating_products.md
This change updates the product ID used in the examples of the
walkthrough for creating products to match the updated product XML file.
=> Update product ID to match updated XML file

ci/website.dockerfile
=> Add 0.3 API docs to published docker image

.github/workflows/merge.yaml
=> Add just to publish_docker workflow step

ci/website.dockerfile, community/planning/features.md, community/planning/griddle/index.md, community/planning/griddle/openapi.yaml, community/planning/roadmap.md, docker-compose.yaml, docker/grid-docs-apache
This adds the proposed Griddle REST API to the community planning section on the Grid website.
=> Add proposed Griddle REST API

_includes/0.3/left_sidebar.html, community/planning/roadmap.md, docs/0.3/workflow_specification.md
Adds a "feature doc" for workflow, with content taken from the RFC.
=> Add workflow specification page

docs/0.3/purchase_order_family_specification.md
Resolve divergence between purchase order specification page in
v0.3 and RFC.
=> Update PO spec to align with RFC

docs/0.3/purchase_order/test_po.xml, docs/0.3/purchase_order_family_specification.md, docs/0.3/using_purchase_order.md
This updates the using purchase order walkthrough to work with the
updated CLI.
=> Update po walkthrough

docs/0.3/grid_purchase_order.md
Changes the PO feature overview to be less technical and more
business-focused. This brings it in line with the other feature
overviews.
=> Make PO feature description more business-focused

community/planning/batch_tracking_store.md, community/planning/features.md
This adds a document giving an overview of the proposed batch tracking store. This document gives a brief overview of the purpose of the component and some proposed structs, traits, and DB schema.
=> Add planning document for Batch Tracking Store

community/planning/batch_tracking_store.md
This updates the Batch Store planning doc structs by renaming the
`Batch` and `Transaction` structs to `GridBatch` and `GridTransaction`.
This is to alleviate any confusion about the differences between these
structs and their counterparts in Transact.
=> Update Batch store planning doc

community/planning/batch_tracking_store.md
This updates the BatchTrackingStore planning docs to bring them
up-to-date with some minor changes that happened while implementing.
=> Update BatchTrackingStore planning docs

docker/schemaspy/0-1/postgres/generate, docker/schemaspy/0-2/postgres/generate, docker/schemaspy/0-3/postgres/generate, docker/schemaspy/0-4/postgres/generate
Java version was updated in PR
https://github.com/schemaspy/schemaspy/pull/850
=> Update schemaspy java dependency version

_includes/head.html, _includes/mermaid.html, css/custom.css
To add a diagram, add the following Jekyll front matter to the
top of the page:
---
tags: [Mermaid]
mermaid: true
---
Next, add the mermaid syntax wrapped in a <div class="mermaid">:
<div class="mermaid">
graph LR
1 --- 2
2-->A[foo]
2-->B(bar)
</div>
=> Add files to generate mermaid diagrams

docs/0.4/creating_splinter_circuits.md
This change updates the walkthrough that explains how to make a Splinter
circuit using the Grid docker-compose example. Grid's Splinter
dependency was updated to v0.6, which changed the API slightly. Mainly,
this removes the `--key` and `--url` options and updates the command
output.
This change also adds a copyright to the top of the file.
=> Update walkthrough of creating a circuit with splinter v0.6

community/planning/dlt_polling_monitor.md
Closes #339 
Also updates the documentation for public traits and structs
=> Add batch tracking sequence diagrams

community/planning/batch_submitter.md
Adds implmentation details and diagrams to the batch submitter design
doc.
=> Update submitter design doc to match impl

community/planning/features.md, community/planning/ha_plan.md
Outlines the high availability plan for the submitter and queuer
subcomponents. This is a first draft; the plan is subject to change.
=> Add design doc for HA plan

community/planning/features.md, community/planning/grid_document.md
=> Add Grid Document spec
