- generator/entrypoint-gen.sh
The URL paths in Jenkins are significantly different from the various
Sawtooth projects.
Signed-off-by: Sutrannu <bbetts@bitwise.io>
> Update Jenkins paths

- generator/source/_sass/base/_global.scss
By default, list-lines and wrapped-list-lines are indented equally.
The theme in use eliminates all padding, including the indentation
of lists. This applies default padding and settings to lists. BIP-379
Signed-off-by: Sutrannu <bbetts@bitwise.io>
> Make lists conform to the standard style

- generator/source/index.md
- Move "Hyperledger Grid" title to banner image
- Rewrite content: Update the high-level overview; add "open source"
and "we welcome contributors" blurbs
- Add links to other website pages, the grid repo, and "Grid in the news"
(the hyperledger-grid category on hyperledger.org)
Other information (from the previous home page) will move to the About page
in a separate PR.
> Update home page for grid-website

- generator/source/faq/faq.rst
- generator/source/faq/grid.rst
- Fix FAQ presentation, organization, and usability
- Add direct links to questions from main page
- Retitle and reorganize the general page
- Remove mini-nav buttons:
(a) There's only one FAQ page right now
(b) "Next" and "Previous" are not meaningful in a FAQ
Will handle nav differently if the FAQ ever gets too large.
- Rewrite "What is Hyperledger Grid" to match new overview on home page (in a separate PR)
- Add more FAQ questions/answers
- Rewrite "Contributing to this FAQ" for clarity
> Reformat, rewrite, and expand FAQ for grid-website

- _includes/0.1/left_sidebar.html
- docs/0.1/references/api/index.md
The TOC link points to the existing "REST API Reference" landing page (this PR fixes two typos on that page).
> Add Grid REST API link to doc left-nav TOC

- docs/0.1/cli_references.md
- Remove "grid agent" usage (and copy pasta) from the "grid agent update" block
- Remove duplicate descriptions from all usage blocks (the content is in the intro sentence)
- Clarify notes for product & schema create/update: Move note to new line and indent to make skimming easier
- Fix typos, formatting, and capitalization
- Correct alphabetic order of subcommands
> Fix issues in CLI reference (grid usage)

- _includes/community/left_sidebar.html
- community/best_practices/feature_documentation.md
Checklist and description of the documentation needed for Grid features such as Product, Location, and Identity.
Note: This file doesn't yet describe where to put the doc files in the grid-docs repo. I'll add this info later (after the directory structure exists).
> Add best-practices info for feature documentation

- community/roadmap.md
This commit handles an undocumented Markdown quirk: It appears that the doc links in a table must have an .html extension (to point to the published file), rather than a .md extension (for the source file)
> Fix doc links in Roadmap table

- community/roadmap.md
This corrects the URL construction on the page to be inline with our
best practice to use liquid-style links. This helps detect broken links
when Jekyll compiles the page.
> Use Jekyll liquid-style link format in roadmap page

- docs/grid/nightly/master/index.md
In case of old bookmarks to the Grid docs source in the grid repo, add an index.md file that redirects to the doc landing page for the Grid docs.
> Add index.md in grid/nightly/master redirect dir

- apache/rewrite.conf
- ci/website.dockerfile
- docker/grid-docs-apache
Moves management of rewrite rules out of Dockerfiles into a single file
shared by the development image and the deployable website image.
> Add rewrite.conf for apache rewrite rules

- _includes/0.1/left_sidebar.html
- Create a new "For Administrators" section" in the doc left-nav contents.
This section will contain links to the new how-to procedures such as Creating a Circuit, Creating Organizations, and Creating Products, etc.
- Move "Running Grid on Splinter" to this section
NOTE: This PR is the required first step for splitting up the how-to procedures in "Running Grid on Splinter".  The subsequent PRs to add these procs as separate how-to topics will add links under "For Administrators". 
> New For Administrators section in doc contents

- _includes/0.1/left_sidebar.html
- docs/0.1/using_grid_features.md
This new topic summarizes the recommended order of using Grid features, such as Grid Product (org/agents first, then schema, then product). It also lists the requirements for using Grid features (2+ grid nodes; connected by a circuit for Grid on Splinter) and links to the available topics for those procedures.
- As separate Grid how-to procedures are added, this topic will link to those procedures.
- Each separate topic will have a "Next Steps" section that links back to this topic. 
This approach isolates the impact of link changes when a new how-to procedure is added; only this file will need to be updated with the new link.
This PR also adds this new topic under "For Administrators" in the doc's left-nav table of contents.
> New "Using Grid Features" doc topic

- _includes/0.1/left_sidebar.html
- docs/0.1/creating_splinter_circuits.md
- docs/0.1/grid_on_splinter.md
- docs/0.1/using_grid_features.md
This new how-to procedure expands the original circuit-creation steps (from "Running Grid on Splinter") with prerequisites, clarifying info, corrections, and subheadings for navigation. Plus a new section on determining the fully qualified service ID and setting GRID_SERVICE_ID to this value.      
Although the intro, nav, service ID info, and linking content is new, the example commands are exactly the same as in "Running Grid on Splinter". The only differences:
- Added output for "splinter circuit propose"                                   
- Replaced a pair of angle brackets with curly braces                           
- Add example of "splinter circuit show $CIRCUIT_ID" for the accepted circuit, so that this section shows both the list and show subcommands.
(The "Next Steps" section …
> Add separate "Creating Splinter Circuits" procedure

- docs/0.1/cli_references.md
- docs/0.1/references/cli/grid-agent-create.1.md
- docs/0.1/references/cli/grid-agent-update.1.md
- docs/0.1/references/cli/grid-agent.1.md
- docs/0.1/references/cli/grid-database-migrate.1.md
- docs/0.1/references/cli/grid-database.1.md
- docs/0.1/references/cli/grid-keygen.1.md
- docs/0.1/references/cli/grid-organization-create.1.md
- docs/0.1/references/cli/grid-organization-update.1.md
- docs/0.1/references/cli/grid-organization.1.md
- docs/0.1/references/cli/grid-product-create.1.md
- docs/0.1/references/cli/grid-product-delete.1.md
- docs/0.1/references/cli/grid-product-list.1.md
- docs/0.1/references/cli/grid-product-show.1.md
- docs/0.1/references/cli/grid-product-update.1.md
- docs/0.1/references/cli/grid-product.1.md
- docs/0.1/references/cli/grid-schema-create.1.md
- docs/0.1/references/cli/grid-schema-list.1.md
- docs/0.1/references/cli/grid-schema-show.1.md
- docs/0.1/references/cli/grid-schema-update.1.md
- docs/0.1/references/cli/grid-schema.1.md
- docs/0.1/references/cli/grid.1.md
Add the initial pass at the CLI reference. Currently only the `grid`
command and `grid product ...` subcommands have full man pages. The
other subcommands simple show the basic usage statement.
> Initial CLI reference

- _includes/0.1/left_sidebar.html
- docs/0.1/grid_product_catalog_smart_contract_specification.md
Adds the Grid Product Catalog smart contract spec to the docs. This
specification is derived from the Grid Product Catalog RFC. Some minor
tweaks have been made in the addressing section around the storage
addresses of Catalogs and Catalog Products.
> Add Grid Product Catalog spec

- _includes/0.1/left_sidebar.html
Also put the new Product Catalog spec in alphabetic order and capitalize the S in "Location Specification"
Moved the Product Catalog spec to the top of the list
> Fix typo after Building Grid link

- _includes/0.1/left_sidebar.html
- docs/0.1/creating_organizations.md
- docs/0.1/grid_on_splinter.md
- docs/0.1/using_grid_features.md
This new how-to procedure expands the original organization-creation steps (from "Running Grid on Splinter") with prerequisites, clarifying info, corrections, and subheadings for navigation. It also includes a section on setting Grid environment variables.
This PR also removes the organization and agent steps from Running Grid on Splinter. and replaces them with a link to the "Creating Organizations" procedure.        
Note: The product-creation steps will be removed in a separate PR. This commit renumbers the product-creation steps and reworks the environment variable info (changed to a note) for those steps.
> Add new Creating Organizations procedure

- docs/0.1/grid_on_splinter.md
Remove the product-creation steps from "Running Grid on Splinter" and replace with a link to the "Creating Products" procedure.
Note: Also add the intro sentence and preceding bullet item to minimize merge conflicts when the "Creating Organizations" PR is merged.
> Replace product steps with link to how-to proc

- _includes/0.1/left_sidebar.html
- docs/0.1/grid_on_splinter.md
- docs/0.1/uploading_smart_contracts.md
This is a Grid-specific version of the information in the Splinter documentation, using the grid/examples/splinter docker-compose file as an example.
Also remove the now-duplicate steps to upload a smart contract from "Running Grid on Splinter".
> Add Uploading Smart Contracts procedure

- docs/0.1/glossary.md
Add new terms:
- agent
- batch
- circuit
- Grid daemon (gridd)
- GS1
- Hyperledger Sawtooth
- namespace
- node
- product
- Splinter
- state delta export
Also: 
- Delete entries for Grid features/smart contracts: Grid Product, Grid Track and Trace, Pike, and Schema.
That information is/will be available in the feature overviews (in the Features section)
- Fix formatting and capitalization
> Update Grid glossary with new terms and corrections

- SECURITY.md
- community/contributing.md
- community/index.md
- community/issue_tracking.md
Updates the info in the contributing sections to reference Github Projects instead of Jira
> Change jira references to github projects

- docs/0.1/cli_references.md
- docs/0.1/references/cli/gridd.1.md
This adds the man page for the gridd command-line command and adds a link to it on the CLI reference page.
> Add gridd man page

- ci/website.dockerfile
- docker/grid-docs-redoc
The node base image was recently updated causing builds to fail
during installation of redoc. Once the issue described at
https://github.com/Redocly/redoc/issues/1442 is resolved, this
change should be reverted.
> Change Dockerfiles to use Node LTS

- ci/website.dockerfile
- docker/grid-docs-redoc
The "latest" image is based off stretch so lts-stretch is a better
replacement. This commit and commit 5753990c should be reverted
once https://github.com/Redocly/redoc/issues/1442 is resolved.
> Switch Dockerfiles to use node:lts-stretch

- docs/0.1/creating_organizations.md
This adds additional, optional steps to the creating organizations page.
Steps to update an organization and add additional agents now follow the
existing procedure.
> Add additional actions to creating orgs docs

- _includes/0.1/left_sidebar.html
- docs/0.1/grid_on_sawtooth.md
- docs/0.1/using_grid_features.md
This adds the "Running Grid on Sawtooth" procedure. This is similar to the "Running Grid on Splinter" procedure but omits mention of circuits as that is not a feature of Sawtooth.
> Add Grid on Sawtooth procedure

- docs/0.1/references/api/openapi.yaml
This commit is a heavy edit of the Grid REST API specification. The
specification was outdated and had many structural and consistency
issues. Due to the scope of changes, the spec was rewritten from scratch
but pulls in some models and structure from the previous version as
appropriate.
In summary, the following changes were made:
- Updated the info object
- Added documentation and links to transaction routes
- Standardized summary and description format
- Removed inaccurate error types
- Organized schemas and paths by feature
> Overhaul Grid REST API spec

- _includes/0.1/left_sidebar.html
- docs/0.1/references/addressing_reference.md
Adds a table reference showing the addresses for all Grid smart contracts.
> Add addressing reference

- docker/compose/grid-website.yaml
This compose file is to be used when deploying the live website, not
for test or development use. Place .scar files in `/opt/grid-website/scar`
and they will be available on the website in the /scar directory.
> Add compose file for running grid-docs website

- .gitignore
- _config.yml
- _includes/0.1/left_sidebar.html
- docker-compose.yaml
- docker/grid-docs-apache
- docker/schemaspy/Dockerfile
- docker/schemaspy/generate
- docker/schemaspy/pgsql11.properties
- docs/0.1/references/database/index.md
This adds the schemaSpy-generated website containing the postgres grid
db docs. To test: run `just run` from the root and navigate to the
"Database Reference" section in the left navbar.
> Add postgres DB docs site

- docs/0.1/creating_schemas.md
This updates the schema procedure to use `docker cp` instead of `cat` to
create the YAML file. `cat` sometimes caused issues with incorrect
formatting. This change reflects similar changes in the location and
product procedures.
> Update schema procedure

- docs/0.1/creating_products.md
- docs/0.1/creating_schemas.md
This adds missing prerequisite information for running in a
grid-on-sawtooth environment to the `creating-<x>` procedures.
> Add missing sawtooth environment info

- docker/schemaspy/generate
- docs/0.1/references/cli/grid-database-migrate.1.md
This updates the database migrate commands to use the new `-C` argument
to pass the connection string. This replaces the `--database-url` arg.
> Update database migrate commands

- community/join_the_discussion.md
- community/planning/roadmap.md
The current terminology for our monthly meetings is 'Grid Community
Meeting'
> Update name of monthly meeting from contributor to community

- _includes/0.2/left_sidebar.html
This adds a link for the Pike overview to the left nav for the 0.2
version of the docs.
> Add Pike overview to 0.2 navigation

- docs/0.2/using_pike.md
This updates the `grid organization update` example command with the
correct flags and replaces the location value with a GLN rather than a
street address.
> Update `grid organization update` example

- docs/0.2/grid_product.md
Adds references to the GDSN specific functionality to the Product feature documentation. Also removes references to the application identifier pattern which is no longer the default.
> Rework product documentation for GDSN

- docs/0.2/creating_locations.md
This adds the owner field to the location schema example. This field is
now required to be present in either the yaml or passed via the CLI.
> Add owner to location schema example

- _includes/0.2/left_sidebar.html
- docs/0.2/upgrading_smart_contracts_for_administrators.md
- docs/0.2/upgrading_smart_contracts_for_developers.md
This adds guides for upgrading a smart contract to a new version. This
splits the procedure into two docs, one for developers and one for
administrators
> Add guide for upgrading smart contracts

- docs/0.2/creating_schemas.md
This updates the "Update schema" section of the "Creating Schemas"
procedure to clarify that an updated schema definition cannot remove or
modify existing properties in order to preserve the validity of existing
data.
> Update "Creating Schemas" procedure

- community/planning/features.md
- community/planning/high_low_level_transaction_rest_api.md
This change adds the feature doc for a proposed High- and Low-level transaction REST API.  The design goal is to all for clients to submit transactions in a simplified manner, using standard JSON structs, removing the need to use or understand the binary wire protocols, as well as the need for any grid-specific client SDKs.
> Add "High- and Low-level Transaction REST API" doc

- _includes/0.3/left_sidebar.html
- docs/0.3/purchase_order_family_specification.md
This change adds a smart contract specification based on the Purchase Order
RFC.
> Add Purchase Order smart contract specification

- _includes/0.3/left_sidebar.html
- docs/0.3/using_purchase_order.md
This adds a preliminary walkthrough for the vendor-managed purchasing scenario
described in the RFC. This will likely need to be updated as development
progresses.
> Add purchase order walkthrough

- _includes/0.3/left_sidebar.html
- docs/0.3/grid_purchase_order.md
Add some high-level information for Purchase Order.
I noticed some issues with the data models while doing this (especially with the alternate IDs). I put some initial changes in here, but I am also going to double check and propose some changes to them in the RFC.
> Add high-level PO documentation

- releases/0.1/download.md
- releases/0.2/download.md
This change updates the links used in the `Releases` pages for Grid v0.1
and v0.2 to update the GitHub link to point to the specific release
branch. This change also adds a note to these release pages to specify
that the released version exists on a branch, rather than just the core
repository.
> Update release pages to link to release branch

- docker-compose.yaml
This fixes an authentication error in Schemaspy after the Postgres 14
release.
trust authorization is not recommended for deployed databases, but is
acceptable in this instance because the database is only being used to generate
schema for documentation purposes.
> Change `POSTGRES_HOST_AUTH_METHOD` to `trust`

- ci/website.dockerfile
This fixes the location of the API doc when the website is getting
built. Previously, the file was being overwritten.
> Fix location of API doc

- community/planning/roadmap.md
This change updates the Grid roadmap page to include a section for the
v0.4 release planned features. This change also rearranges the page to
indicate v0.3 as the "latest" release and to make past releases more
readable.
> Update Grid roadmap for future releases

- docs/0.3/glossary.md
- docs/0.3/grid_on_sawtooth.md
- docs/0.3/grid_on_splinter.md
- docs/0.3/references/addressing_reference.md
- docs/0.3/upgrading_smart_contracts_for_administrators.md
- releases/0.2/index.md
- releases/0.3/index.md
- releases/0.3/upgrading/README.md
- releases/0.3/upgrading/grid-v0.3.1-from-v0.2.3.md
This adds a brief upgrading procedure for upgrading Grid from version
0.2 to version 0.3. Other sections are also updated to include references to
the addition of Purchase Order functionality.
Signed-off-by: Davey Newhall newhall@bitwise.io
> Update Grid docs for 0.3 release

- docs/0.3/cli_references.md
- docs/0.3/references/cli/grid-download-xsd.1.md
- docs/0.3/using_purchase_order.md
- docs/0.4/cli_references.md
- docs/0.4/references/cli/grid-download-xsd.1.md
- docs/0.4/using_purchase_order.md
Currently this is only used if the user is attempting to add a purchase
order. Also added a link to the manpage for in depth instructions (such
as manually downloading the cache files).
Signed-off-by: Lee Bradley <bradley@bitwise.io>
> Add instructions for `download-xsd`

- docker-compose.yaml
The `--host` flag was added, which defaults to 127.0.0.1.
https://github.com/Redocly/redoc/pull/1598
> Add flag so redoc containers listen on all interfaces

- docs/0.3/grid_on_splinter.md
- docs/0.4/grid_on_splinter.md
Updates include adding references to Purchase Order, updating
references to Splinter docs, formatting, adding missing references
to existing smart contracts, and replacing the reference to the XO
contract with an example using Purchase Order. Updates 0.3 and 0.4
docs.
> Update Using Grid on Splinter

- docs/0.2/creating_splinter_circuits.md
- docs/0.2/grid_on_splinter.md
- docs/0.3/creating_splinter_circuits.md
- docs/0.3/grid_on_splinter.md
- docs/0.4/creating_splinter_circuits.md
- docs/0.4/grid_on_splinter.md
Fixes the commands to enter a bash session in a node. Also makes a
few small text fixes. Updates 0.3 and 0.2 docs.
> Fix docker exec splinterd bash commands

- docs/0.2/creating_schemas.md
- docs/0.2/using_pike.md
- docs/0.3/creating_schemas.md
- docs/0.3/using_pike.md
- docs/0.4/creating_schemas.md
- docs/0.4/using_pike.md
Corrects section on updating schemas, fixes minor issues in text,
and adds the schema update permission to the Using Pike page.
Updates 0.3, 0.4, and 0.2.
> Update Creating Schemas

- docs/0.2/upgrading_smart_contracts_for_administrators.md
- docs/0.3/upgrading_smart_contracts_for_administrators.md
- docs/0.4/upgrading_smart_contracts_for_administrators.md
Adds a warning for users to save their keys before rebuilding the
daemons. Also fixes a typo.
> Update Upgrading Smart Contracts

- docs/0.2/creating_locations.md
- docs/0.3/creating_locations.md
- docs/0.4/creating_locations.md
This change fixes the line in the `Creating Locations` guide used to
create the role with permissions to create, update, and delete a
location. Previously, the list of permissions was broken up by a `\` to
allow it to span multiple lines. However, this was creating a space in
the `location::can-delete-location` permission that disabled Grid from
being able to recognize this permission. This change removes the back
slash and keeps the permissions on one line, which still allows for
linting to pass and does not cause a space to occur in the permissions
string.
> Fix permissions for using Grid Location

- docs/0.3/references/cli/grid-keygen.1.md
- docs/0.4/references/cli/grid-keygen.1.md
This adds the KEY_NAME argument to the grid keygen man page.
> Update `grid keygen` man page

- ci/website.dockerfile
This change fixes the file path used to locate the API docs when
building the site. This change removes the `references` level in the
path.
> Fix API doc path for building website

- community/images/grid_batch_submitter.svg
- community/planning/batch_submitter.md
Updates the batch submitter design doc in the community planning section
with background and planning for the component.
The previous design doc was incompatible with the new, broad batch
submission and tracking design.
> Update batch submitter design doc

- community/planning/features.md
- community/planning/rest_api/backwards_compatibility.md
- community/planning/rest_api/index.md
Add a plan for testing Grid and Splinter REST API compatibility between
versions.
Signed-off-by: Lee Bradley <bradley@bitwise.io>
> Add REST API Backwards Compatibility Plan

- community/images/grid_batch_submitter.svg
- community/planning/batch_submitter.md
Adds explanations of the submitter-related traits and implementations
to the submitter design doc. Also updates parts of the existing doc to
match the actual implementation.
> Update batch submitter doc with impl. details

- community/planning/dlt_event_monitor.md
- community/planning/dlt_polling_monitor.md
- community/planning/features.md
Add feature documentation for building the DLT Event Monitor from
streams coming from either Sawtooth or Splinter.
Signed-off-by: Lee Bradley <bradley@bitwise.io>
> Add DLT Event Monitor feature doc

- community/planning/features.md
- community/planning/griddle_proxy.md
This changes adds a document for the proposed Griddle proxy
functionality. This doc is linked to from the community/planning section
of the Grid site.
> Add doc for Griddle proxy functionality

- community/planning/dlt_event_monitor.md
The DLT event monitor document previously called for batch updates to
happen in real-time as they came in from the DLT stream. Unfortunately,
the current implementation of the DLT event stream does not include
sufficient information to allow a useful batch status update. This
change proposes an alternate solution: The DLT event monitor uses events
as a cue that a batch was updated. It then calls out to the polling
monitor, which gathers the associated batch information.
Signed-off-by: Lee Bradley <bradley@bitwise.io>
> Add polling calls to DLT event monitor document

- _layouts/landing_page.html
- community/best_practices/feature_documentation.md
- community/planning/rest_api/openapi.yaml
- docs/0.1/glossary.md
- docs/0.1/references/api/openapi.yaml
- docs/0.1/uploading_smart_contracts.md
- docs/0.2/glossary.md
- docs/0.2/references/api/openapi.yaml
- docs/0.2/uploading_smart_contracts.md
- docs/0.3/glossary.md
- docs/0.3/references/api/openapi.yaml
- docs/0.3/uploading_smart_contracts.md
- docs/0.4/glossary.md
- docs/0.4/references/api/openapi.yaml
- docs/0.4/uploading_smart_contracts.md
The Sawtooth docs site recently underwent a reorganization. This PR fixes the existing links for the updated Sawtooth docs.
> Fix links to Sawtooth documentation

- community/planning/features.md
- community/planning/queuer_strat_one_round_serial.md
Add details of algorithm and implementation of one-round serial queuing
strategy.
> Add design doc for one-round serial queuer

- docs/0.3/building_grid.md
- docs/0.4/building_grid.md
Update the local build instructions in the Grid documentation so they
always references the latest canonical list of prerequisites as outlined
in the repo's README.md file.
Signed-off-by: Amelia Bradley <bradley@bitwise.io>
> Update local build instructions to references deps

- community/planning/features.md
- community/planning/queuer_strat_one_round_parallel.md
Adds a doc to community/planning that examines the feasibility and practicality of one-round parallel queuing strategies.
> Add research doc for one-round parallel queuer

- docs/0.3/creating_splinter_circuits.md
This change updates the main walkthrough for creating a splinter circuit
to include directions for when one or both of the nodes are running Splinter
0.6.
> Update creating a circuit with Grid 0.3
